spring:
  application:
    name: portfolio
  profiles:
    active: local

  datasource:
    url: jdbc:mariadb://localhost:3306/dbbaroportfolio
    username: root
    password: jhlee

server:
  servlet:
    session:
      tracking-modes: cookie

mybatis:
  type-aliases-package: com.baro.portfolio.domain
