spring:
  application:
    name: portfolio
  profiles:
    active: local
  messages:
    basename: messages

  datasource:
    url: jdbc:mariadb://localhost:3306/dbbaroportfolio
    username: root
    password: jhlee

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 60
  error:
    include-exception: false
    include-message: always
    include-stacktrace: never
    include-binding-errors: never
    whitelabel:
      enabled: true

mybatis:
  type-aliases-package: com.baro.portfolio.domain
